package com.springmvc.mapper;

import com.springmvc.model.UcommentWithBLOBs;

public interface UcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucomment
     *
     * @mbg.generated
     */
    int insert(UcommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucomment
     *
     * @mbg.generated
     */
    int insertSelective(UcommentWithBLOBs record);
}